# This file must to be changed for each project
defaultProject: conversionista-se
defaultLocation: EU
defaultDataset: dataform_funnels_c_test_Arina
dataformCoreVersion: 3.0.0

vars:
  sourceDataset: non_copy_analytics_305832606
  sourceTable: events_*
  funnelStages: "view_item, select_item, add_to_cart, begin_checkout, purchase "
  granularity: "daily" # Options: "daily", "weekly", "monthly"
  # If you want to add customized events (those that are not specifically tracked),
  # you need to change the function generateSelectColumns in general_functions.js

  dimensions : "device.category"
  #dimensions : ""
  dateRangeStart: "20241001"
  dateRangeEnd: "20241110"
  daysAgo : "3"
  columnsToExtract: '{
    "event_params": [
      {"name": "ga_session_id", "type": "int_value"},
      {"name": "page_location", "type": "string_value"}
    ],
    "item.item_params": [
      {"name": "own_brand", "type": "int_value"}
    ]
    }'

  filters: '{
    #"geo.country": ["Sweden", "Norway"],
    "device.category": ["mobile", "desktop"]
  }'

  stagedColumns: '[
    {"name": "event_date", "description": "Date of the event"},
    {"name": "event_timestamp", "description": "Timestamp of the event"},
    {"name": "event_name", "description": "Name of the events"},
    {"name": "user_pseudo_id", "description": "User ID"},
    {"name": "ga_session_id", "description": "Session ID"},
    {"name": "purchase_revenue", "description": "Purchase revenue"},
    {"name": "total_quantity", "description": "Total item quantity"},
    {"name": "device_category", "description": "Device cateogory"},
    {"name": "page_location", "description": "Page location"}
  ]'


  columnMappings: '{
    "date": "event_date",
    "timestamp" : "event_timestamp",
    "event_name": "event_name",
    "user_id": "user_pseudo_id",
    "session_id": "ga_session_id",
    "purchase_revenue":"ecommerce.purchase_revenue",
    "total_quantity": "ecommerce.total_item_quantity",
    "device_category": "device.category"
  }'
  
