config {
    type: "incremental",
    name: "closed_user_funnel",
    description: "Closed user funnel based on staged GA4 data, grouped by date and specified dimensions",
    dependencies: ["staged_data"],
    bigquery: { 
         partitionBy: "event_date"
     }
}

js {
    const {
        sanitizeColumnName,
        mapColumnName,
        getDateDaysAgo
    } = require('../includes/general_functions.js');
    const {
        generateStageCounts,
        generateGroupByColumns,
        generateStageCTEs,
        generateStageSums,
        generateFunnelQuery
    } = require('../includes/funnel_functions.js');

    const stagedColumns = JSON.parse(dataform.projectConfig.vars.stagedColumns);
    const funnelStages = dataform.projectConfig.vars.funnelStages.split(',').map(stage => stage.trim());
    const dimensions = dataform.projectConfig.vars.dimensions ?
        dataform.projectConfig.vars.dimensions.split(',').map(dim => dim.trim()) : [];
    const columnMappings = JSON.parse(dataform.projectConfig.vars.columnMappings);
    const daysAgo = JSON.parse(dataform.projectConfig.vars.daysAgo);
}

WITH
  source_data AS (
  SELECT
    *
  FROM
    ${ref("staged_data")}
  WHERE ${mapColumnName('date', columnMappings)} ${when(incremental(), 
    `= '${getDateDaysAgo(daysAgo)}'`,
    `BETWEEN PARSE_DATE('%Y%m%d', '${dataform.projectConfig.vars.dateRangeStart}') AND PARSE_DATE('%Y%m%d', '${dataform.projectConfig.vars.dateRangeEnd}')`
  )}
    ),
  ${generateStageCTEs(funnelStages, dimensions, columnMappings, 'user')} ${generateFunnelQuery(funnelStages, dimensions, columnMappings, 'user')}
