config {
  type: "incremental",
  name: "open_session_funnel",
  description: "Open session funnel based on staged GA4 data, grouped by date and event name",
  dependencies: ["staged_data"]
}

js {
  const { sanitizeColumnName, mapColumnName, getIncrementalDateRange } = require('../includes/general_functions.js');
  const daysAgo = JSON.parse(dataform.projectConfig.vars.daysAgo);
  const stagedColumns = JSON.parse(dataform.projectConfig.vars.stagedColumns);
  const funnelStages = dataform.projectConfig.vars.funnelStages.split(',').map(stage => stage.trim());
  const dimensions = dataform.projectConfig.vars.dimensions ? 
      dataform.projectConfig.vars.dimensions.split(',').map(dim => dim.trim()) : [];
  const columnMappings = JSON.parse(dataform.projectConfig.vars.columnMappings);
  const granularity = dataform.projectConfig.vars.granularity;
  const dateRange = getIncrementalDateRange(granularity, daysAgo);
}

SELECT
  CASE '${granularity}'
    WHEN 'daily' THEN PARSE_DATE('%Y%m%d', ${sanitizeColumnName(mapColumnName('date', columnMappings))})
    WHEN 'weekly' THEN DATE_TRUNC(PARSE_DATE('%Y%m%d', ${sanitizeColumnName(mapColumnName('date', columnMappings))}), ISOWEEK)
    WHEN 'monthly' THEN DATE_TRUNC(PARSE_DATE('%Y%m%d', ${sanitizeColumnName(mapColumnName('date', columnMappings))}), MONTH)
    ELSE PARSE_DATE('%Y%m%d', ${sanitizeColumnName(mapColumnName('date', columnMappings))})
  END AS event_date,
  ${mapColumnName('event_name', columnMappings)} AS event_name,
  COUNT(DISTINCT ${mapColumnName('session_id', columnMappings)}) AS event_count
  /*,SUM(purchase_revenue) AS total_revenue,
  SUM(CASE WHEN ${mapColumnName('event_name', columnMappings)} = 'purchase' THEN total_quantity ELSE 0 END) AS total_item_quantity*/
  ${dimensions.length > 0 ? ', ' + dimensions.map(dim => sanitizeColumnName(mapColumnName(dim, columnMappings))).join(', ') : ''}
FROM ${ref("staged_data")}
WHERE 
  ${mapColumnName('date', columnMappings)} ${when(incremental(), 
    `BETWEEN '${getIncrementalDateRange(granularity, daysAgo).startDate}' AND '${getIncrementalDateRange(granularity, daysAgo).endDate}'`,
    `BETWEEN '${dataform.projectConfig.vars.dateRangeStart}' AND '${dataform.projectConfig.vars.dateRangeEnd}'`
  )}
  AND ${mapColumnName('event_name', columnMappings)} IN (${funnelStages.map(stage => `'${stage}'`).join(', ')})
GROUP BY 
  event_date,
  ${mapColumnName('event_name', columnMappings)}
  ${dimensions.length > 0 ? ', ' + dimensions.map(dim => sanitizeColumnName(mapColumnName(dim, columnMappings))).join(', ') : ''}
ORDER BY 
  event_date,
  ${mapColumnName('event_name', columnMappings)}
  ${dimensions.length > 0 ? ', ' + dimensions.map(dim => sanitizeColumnName(mapColumnName(dim, columnMappings))).join(', ') : ''}