config {
    type: "incremental",
    name: "staged_data",
    description: "Incremental table for staged data with extracted nested parameters, filtered by specified funnel stages",
    bigquery: { 
         partitionBy: "event_date"
     }
}


js {
    // Import functions from the external JavaScript file
    const {
        sanitizeColumnName,
        mapColumnName,
        generateSelectColumns,
        generateFinalSelectColumns,
        generateFunnelStagesFilter,
        generateFilters,
        publishStagedData,
        getDateDaysAgo
    } = require('../includes/general_functions.js');

    const stagedColumns = JSON.parse(dataform.projectConfig.vars.stagedColumns);
    const columnsToExtract = JSON.parse(dataform.projectConfig.vars.columnsToExtract);
    const funnelStages = dataform.projectConfig.vars.funnelStages.split(',').map(stage => stage.trim());
    const columnMappings = JSON.parse(dataform.projectConfig.vars.columnMappings);
    const daysAgo = JSON.parse(dataform.projectConfig.vars.daysAgo);
    const dimensions = dataform.projectConfig.vars.dimensions ?
        dataform.projectConfig.vars.dimensions.split(',').map(dim => dim.trim()).filter(dim => dim) : [];
    const filters = (() => {
        try {
            return JSON.parse(dataform.projectConfig.vars.filters || '{}');
        } catch (e) {
            return {};
        }
    })();

}

WITH
  source_data AS (
  SELECT
    ${generateSelectColumns(stagedColumns, columnMappings, columnsToExtract)}
  FROM
    `${dataform.projectConfig.vars.sourceDataset}.${dataform.projectConfig.vars.sourceTable}`
  WHERE
    ${
        when(incremental(),
            `_TABLE_SUFFIX = '${getDateDaysAgo(daysAgo)}'`,
            `_TABLE_SUFFIX BETWEEN '${dataform.projectConfig.vars.dateRangeStart}' AND '${dataform.projectConfig.vars.dateRangeEnd}'`
        )
    }
  ),
  filtered_data AS (
  SELECT
    *
  FROM
    source_data 
  WHERE ${mapColumnName('event_name', columnMappings)} IN (${generateFunnelStagesFilter(funnelStages)}) ${generateFilters(filters)} )
SELECT
  ${generateFinalSelectColumns(stagedColumns)}
FROM
  filtered_data
WHERE
  (${mapColumnName('user_id', columnMappings)} IS NOT NULL
    OR ${mapColumnName('session_id', columnMappings)} IS NOT NULL)